### ISSUE TITLE
Paris-streetview pretrained model seems not work

### ISSUE THREAD

**Issue by lymhhhh** [shepnerd/outpainting_srn#15]
```
------------ Options -------------
d_cnum: 64
data_file: ./imgs/celebahq-256/
dataset: paris_streetview
dataset_path: ./imgs/celebahq-256/
date_str: test_20211116-223942
fa_alpha: 0.5
feat_expansion_op: subpixel
g_cnum: 64
img_shapes: [256, 256, 3]
load_model_dir: ./checkpoints/cityscapes-srn-subpixel-gc64
mask_shapes: [128, 128]
model: srn
model_folder: test_20211116-223942_paris_streetview_srn_subpixel_s256x256_gc64_rand-mask_seed-1
model_prefix: snap
random_crop: True
random_mask: True
random_seed: False
saving_path: ./test_results/test_20211116-223942_paris_streetview_srn_subpixel_s256x256_gc64_rand-mask_seed-1
seed: 1
test_dir: ./test_results
test_num: -1
use_cn: True
-------------- End ----------------
The total number of testing images is 8, and we take 8 for test.
WARNING:tensorflow:From /Users/image outpainting/outpainting_srn/net/ops.py:104: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "/Users/leiyiming/opt/anaconda3/envs/outpainting_srn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1589, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 3 in both shapes must be equal, but are 256 and 128. Shapes are [3,3,64,256] and [3,3,64,128]. for 'Assign_30' (op: 'Assign') with input shapes: [3,3,64,256], [3,3,64,128].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/image outpainting/outpainting_srn/test.py", line 79, in <module>
    vars_list))
  File "/Users/image outpainting/outpainting_srn/test.py", line 78, in <lambda>
    assign_ops = list(map(lambda x: tf.assign(x, tf.contrib.framework.load_variable(config.load_model_dir, x.name)),
  File "/Users/leiyiming/opt/anaconda3/envs/outpainting_srn/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 219, in assign
    validate_shape=validate_shape)
  File "/Users/leiyiming/opt/anaconda3/envs/outpainting_srn/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/Users/leiyiming/opt/anaconda3/envs/outpainting_srn/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/leiyiming/opt/anaconda3/envs/outpainting_srn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/Users/leiyiming/opt/anaconda3/envs/outpainting_srn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1756, in __init__
    control_input_ops)
  File "/Users/leiyiming/opt/anaconda3/envs/outpainting_srn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1592, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 3 in both shapes must be equal, but are 256 and 128. Shapes are [3,3,64,256] and [3,3,64,128]. for 'Assign_30' (op: 'Assign') with input shapes: [3,3,64,256], [3,3,64,128].
```

**Comment by lymhhhh** [comment]
Problem solved.

**Comment by MasterHow** [comment]
same question, can you give me some help? ：）
