### ISSUE TITLE
ValueError: Dimension 3 in both shapes must be equal, but are 32 and 64. Shapes are [5,5,3,32] and [5,5,3,64]. for 'Assign' (op: 'Assign') with input shapes: [5,5,3,32], [5,5,3,64].

### ISSUE THREAD

**Issue by Haoru** [shepnerd/outpainting_srn#2]
I got this error while doing the testing. Please help me out here.
Traceback (most recent call last):
  File "test.py", line 79, in <module>
    vars_list))
  File "test.py", line 78, in <lambda>
    assign_ops = list(map(lambda x: tf.assign(x, tf.contrib.framework.load_variable(config.load_model_dir, x.name)),
  File "/media/disk/gds/miniconda3/envs/out/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 280, in assign
    validate_shape=validate_shape)
  File "/media/disk/gds/miniconda3/envs/out/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 58, in assign
    use_locking=use_locking, name=name)
  File "/media/disk/gds/miniconda3/envs/out/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/media/disk/gds/miniconda3/envs/out/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3273, in create_op
    compute_device=compute_device)
  File "/media/disk/gds/miniconda3/envs/out/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3313, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/media/disk/gds/miniconda3/envs/out/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2501, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/media/disk/gds/miniconda3/envs/out/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2474, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/media/disk/gds/miniconda3/envs/out/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2404, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/media/disk/gds/miniconda3/envs/out/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/media/disk/gds/miniconda3/envs/out/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 3 in both shapes must be equal, but are 32 and 64. Shapes are [5,5,3,32] and [5,5,3,64]. for 'Assign' (op: 'Assign') with input shapes: [5,5,3,32], [5,5,3,64].

**Comment by shepnerd** [comment]
Try to set `--g_cnum 64` when calling test.py. Or you manually set `g_cnum` to 64 in options/test_options.py.

**Comment by Haoru** [comment]
Thanks for your help. The results in your paper are fine. And could you tell me how many images in the dataset are used for training?

**Comment by shepnerd** [comment]
Generally, we follow the train/test splits in the used dataset, and some of them are given in our supplementary file. For celebA-hq-256, 28k images are used for training and 2k for testing.
